---
title: "Week_1_Task"
author: "Elwood Fong"
date: "2025-02-14"
output: 
  rmdformats::downcute:
    number_sections: false
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("~/Desktop/University/AMED3002/")
```

### Contents
- [Abstract](#abstract)
- [Introduction](#introduction)
- [Results](#results)
- [Discussion](#discussion)
- [Conclusion](#conclusion)

### Abstract {#abstract}


### Introduction {#introduction}
```{r, echo = FALSE}
# Libraries
library(ggplot2)
library(tidyr)

# Raw Data
sleep <- read.csv("StudentTSleepData.csv", row.names=1)
```

```{r}
# Reorganize Data
sleep$patient <- factor(1:10)
sleepLong <- pivot_longer(sleep, cols=c("Dextro", "Laevo"), names_to="treatment", values_to="hours")
```


### Results {#results}
``` {r, NAME, fig.cap = "", echo = TRUE}
# Insert plot
ggplot(sleepLong, aes(x=patient, y=hours, fill=treatment)) + 
  geom_bar(stat="identity", position=position_dodge()) +
  labs(title="Sleep treatment", subtitle="Bar plot", 
       caption="(based on data from Table 1 in Student, 1908)") + 
  ylab("hours")

```


### Discussion {#discussion}


### Conclusion {#conclusion}

